# MVP kinase inhibitor seed — sponsors locked to major pharma for BD benchmarking.
# Join grain: drug ↔ target ↔ openFDA PT. Never patient UUID.

# Full sponsor directory for UI filters (even if no seeded drug yet).
SPONSOR_DIRECTORY = [
  "AbbVie",
  "Amgen",
  "AstraZeneca",
  "Bayer",
  "Biogen",
  "BioNTech",
  "Boehringer Ingelheim",
  "Bristol Myers Squibb",
  "Eli Lilly",
  "Gilead Sciences",
  "GSK (GlaxoSmithKline)",
  "Johnson & Johnson (Janssen)",
  "Merck & Co. (MSD)",
  "Moderna",
  "Novartis",
  "Pfizer",
  "Regeneron",
  "Roche / Genentech",
  "Sanofi",
  "Takeda",
  "Vertex Pharmaceuticals",
]

drugs = [
  {
    "drug_id": "drug_imatinib",
    "preferred_name": "imatinib",
    "brand_name": "Gleevec",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "hematologic_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Novartis",
    "nda_bla": "NDA021588",
    "atc_code": "L01EA01",
    "rxnorm_cui": "282388",
    "chembl_id": "CHEMBL941",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "BCR-ABL / KIT / PDGFR TKI (Gleevec)",
  },
  {
    "drug_id": "drug_erlotinib",
    "preferred_name": "erlotinib",
    "brand_name": "Tarceva",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Roche / Genentech",
    "nda_bla": "NDA021743",
    "atc_code": "L01EB02",
    "rxnorm_cui": "337525",
    "chembl_id": "CHEMBL553",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "EGFR TKI (Tarceva)",
  },
  {
    "drug_id": "drug_gefitinib",
    "preferred_name": "gefitinib",
    "brand_name": "Iressa",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "AstraZeneca",
    "nda_bla": "NDA021399",
    "atc_code": "L01EB01",
    "rxnorm_cui": "328134",
    "chembl_id": "CHEMBL939",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4,CYP2D6",
    "notes": "EGFR TKI (Iressa)",
  },
  {
    "drug_id": "drug_dasatinib",
    "preferred_name": "dasatinib",
    "brand_name": "Sprycel",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "hematologic_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Bristol Myers Squibb",
    "nda_bla": "NDA021986",
    "atc_code": "L01EA02",
    "rxnorm_cui": "668700",
    "chembl_id": "CHEMBL1421",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "BCR-ABL / SRC family TKI (Sprycel)",
  },
  {
    "drug_id": "drug_nilotinib",
    "preferred_name": "nilotinib",
    "brand_name": "Tasigna",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "hematologic_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Novartis",
    "nda_bla": "NDA022068",
    "atc_code": "L01EA03",
    "rxnorm_cui": "662281",
    "chembl_id": "CHEMBL1168",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "BCR-ABL TKI (Tasigna); QT / hepatic warnings",
  },
  {
    "drug_id": "drug_sunitinib",
    "preferred_name": "sunitinib",
    "brand_name": "Sutent",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Pfizer",
    "nda_bla": "NDA021938",
    "atc_code": "L01EX01",
    "rxnorm_cui": "616739",
    "chembl_id": "CHEMBL535",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "VEGFR / PDGFR / KIT multi-kinase (Sutent)",
  },
  {
    "drug_id": "drug_sorafenib",
    "preferred_name": "sorafenib",
    "brand_name": "Nexavar",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Bayer",
    "nda_bla": "NDA021923",
    "atc_code": "L01EX02",
    "rxnorm_cui": "495881",
    "chembl_id": "CHEMBL1336",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "RAF / VEGFR multi-kinase (Nexavar); hand-foot / hepatic",
  },
  {
    "drug_id": "drug_lapatinib",
    "preferred_name": "lapatinib",
    "brand_name": "Tykerb",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Novartis",
    "nda_bla": "NDA022059",
    "atc_code": "L01EH01",
    "rxnorm_cui": "480167",
    "chembl_id": "CHEMBL554",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4,CYP2C8",
    "notes": "EGFR / HER2 TKI (Tykerb); hepatotoxicity BBW",
  },
  {
    "drug_id": "drug_pazopanib",
    "preferred_name": "pazopanib",
    "brand_name": "Votrient",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Novartis",
    "nda_bla": "NDA022465",
    "atc_code": "L01EX03",
    "rxnorm_cui": "891656",
    "chembl_id": "CHEMBL119929",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "VEGFR TKI (Votrient); hepatotoxicity BBW",
  },
  {
    "drug_id": "drug_axitinib",
    "preferred_name": "axitinib",
    "brand_name": "Inlyta",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Pfizer",
    "nda_bla": "NDA202324",
    "atc_code": "L01EK01",
    "rxnorm_cui": "1242988",
    "chembl_id": "CHEMBL1289926",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4,CYP1A2",
    "notes": "VEGFR TKI (Inlyta)",
  },
  {
    "drug_id": "drug_ibrutinib",
    "preferred_name": "ibrutinib",
    "brand_name": "Imbruvica",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "hematologic_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "AbbVie",
    "nda_bla": "NDA205552",
    "atc_code": "L01EL01",
    "rxnorm_cui": "1442986",
    "chembl_id": "CHEMBL1873475",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "BTK inhibitor (Imbruvica); AbbVie / Janssen",
  },
  {
    "drug_id": "drug_osimertinib",
    "preferred_name": "osimertinib",
    "brand_name": "Tagrisso",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "AstraZeneca",
    "nda_bla": "NDA208065",
    "atc_code": "L01EB04",
    "rxnorm_cui": "1727455",
    "chembl_id": "CHEMBL3353410",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "EGFR T790M TKI (Tagrisso)",
  },
  {
    "drug_id": "drug_tofacitinib",
    "preferred_name": "tofacitinib",
    "brand_name": "Xeljanz",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "immunology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Pfizer",
    "nda_bla": "NDA203214",
    "atc_code": "L04AF01",
    "rxnorm_cui": "1356511",
    "chembl_id": "CHEMBL221959",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4,CYP2C19",
    "notes": "JAK inhibitor (Xeljanz)",
  },
  # Biologics / vaccines — populate BioNTech, Moderna, Merck, Sanofi molecule-type filters
  {
    "drug_id": "drug_tozinameran",
    "preferred_name": "tozinameran",
    "brand_name": "Comirnaty",
    "drug_class": "mrna_vaccine",
    "therapeutic_class": "infectious_disease",
    "molecule_type": "biologic",
    "sponsor_company": "BioNTech",
    "nda_bla": "BLA125742",
    "atc_code": "J07BN01",
    "rxnorm_cui": "2468231",
    "chembl_id": "CHEMBL4297850",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "BNT162b2 COVID-19 mRNA vaccine (BioNTech/Pfizer)",
  },
  {
    "drug_id": "drug_elasomeran",
    "preferred_name": "elasomeran",
    "brand_name": "Spikevax",
    "drug_class": "mrna_vaccine",
    "therapeutic_class": "infectious_disease",
    "molecule_type": "biologic",
    "sponsor_company": "Moderna",
    "nda_bla": "BLA125769",
    "atc_code": "J07BN01",
    "rxnorm_cui": "2473488",
    "chembl_id": "CHEMBL4297851",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "mRNA-1273 COVID-19 vaccine (Moderna)",
  },
  {
    "drug_id": "drug_pembrolizumab",
    "preferred_name": "pembrolizumab",
    "brand_name": "Keytruda",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "biologic",
    "sponsor_company": "Merck & Co. (MSD)",
    "nda_bla": "BLA125514",
    "atc_code": "L01FF02",
    "rxnorm_cui": "1547545",
    "chembl_id": "CHEMBL3137343",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-PD-1 mAb (Keytruda)",
  },
  {
    "drug_id": "drug_dupilumab",
    "preferred_name": "dupilumab",
    "brand_name": "Dupixent",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "immunology",
    "molecule_type": "biologic",
    "sponsor_company": "Sanofi",
    "nda_bla": "BLA761055",
    "atc_code": "D11AH05",
    "rxnorm_cui": "1873983",
    "chembl_id": "CHEMBL1743036",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-IL-4Rα mAb (Dupixent); Sanofi/Regeneron",
  },
]

targets = [
  {"target_id": "tgt_egfr", "gene_symbol": "EGFR", "uniprot_id": "P00533", "ensembl_id": "ENSG00000146648", "pdb_id": "1M17", "protein_name": "Epidermal growth factor receptor", "is_admet_relevant": False},
  {"target_id": "tgt_erbb2", "gene_symbol": "ERBB2", "uniprot_id": "P04626", "ensembl_id": "ENSG00000141736", "pdb_id": "3PP0", "protein_name": "Receptor tyrosine-protein kinase erbB-2", "is_admet_relevant": False},
  {"target_id": "tgt_abl1", "gene_symbol": "ABL1", "uniprot_id": "P00519", "ensembl_id": "ENSG00000097007", "pdb_id": "2HYY", "protein_name": "Tyrosine-protein kinase ABL1", "is_admet_relevant": False},
  {"target_id": "tgt_kit", "gene_symbol": "KIT", "uniprot_id": "P10721", "ensembl_id": "ENSG00000157404", "pdb_id": "1T46", "protein_name": "Mast/stem cell growth factor receptor Kit", "is_admet_relevant": False},
  {"target_id": "tgt_pdgfra", "gene_symbol": "PDGFRA", "uniprot_id": "P16234", "ensembl_id": "ENSG00000134853", "pdb_id": "5K5X", "protein_name": "Platelet-derived growth factor receptor alpha", "is_admet_relevant": False},
  {"target_id": "tgt_kdr", "gene_symbol": "KDR", "uniprot_id": "P35968", "ensembl_id": "ENSG00000128052", "pdb_id": "3VHE", "protein_name": "Vascular endothelial growth factor receptor 2", "is_admet_relevant": False},
  {"target_id": "tgt_flt1", "gene_symbol": "FLT1", "uniprot_id": "P17948", "ensembl_id": "ENSG00000102755", "pdb_id": "1QSZ", "protein_name": "Vascular endothelial growth factor receptor 1", "is_admet_relevant": False},
  {"target_id": "tgt_src", "gene_symbol": "SRC", "uniprot_id": "P12931", "ensembl_id": "ENSG00000197122", "pdb_id": "2SRC", "protein_name": "Proto-oncogene tyrosine-protein kinase Src", "is_admet_relevant": False},
  {"target_id": "tgt_braf", "gene_symbol": "BRAF", "uniprot_id": "P15056", "ensembl_id": "ENSG00000157764", "pdb_id": "4RZV", "protein_name": "Serine/threonine-protein kinase B-raf", "is_admet_relevant": False},
  {"target_id": "tgt_cyp3a4", "gene_symbol": "CYP3A4", "uniprot_id": "P08684", "ensembl_id": "ENSG00000160868", "pdb_id": "1TQN", "protein_name": "Cytochrome P450 3A4", "is_admet_relevant": True},
  {"target_id": "tgt_cyp2d6", "gene_symbol": "CYP2D6", "uniprot_id": "P10635", "ensembl_id": "ENSG00000100146", "pdb_id": "3TBG", "protein_name": "Cytochrome P450 2D6", "is_admet_relevant": True},
  {"target_id": "tgt_btk", "gene_symbol": "BTK", "uniprot_id": "Q06187", "ensembl_id": "ENSG00000010671", "pdb_id": "5P9J", "protein_name": "Tyrosine-protein kinase BTK", "is_admet_relevant": False},
  {"target_id": "tgt_jak1", "gene_symbol": "JAK1", "uniprot_id": "P23458", "ensembl_id": "ENSG00000162434", "pdb_id": "6N7A", "protein_name": "Tyrosine-protein kinase JAK1", "is_admet_relevant": False},
  {"target_id": "tgt_pdcd1", "gene_symbol": "PDCD1", "uniprot_id": "Q15116", "ensembl_id": "ENSG00000188389", "pdb_id": "5GGS", "protein_name": "Programmed cell death protein 1", "is_admet_relevant": False},
  {"target_id": "tgt_il4r", "gene_symbol": "IL4R", "uniprot_id": "P24394", "ensembl_id": "ENSG00000077238", "pdb_id": "1IAR", "protein_name": "Interleukin-4 receptor subunit alpha", "is_admet_relevant": False},
  {"target_id": "tgt_spike", "gene_symbol": "S", "uniprot_id": "P0DTC2", "ensembl_id": None, "pdb_id": "6VXX", "protein_name": "SARS-CoV-2 spike glycoprotein", "is_admet_relevant": False},
]

# Representative seed affinities (nM). Phase 1 will overwrite/expand from ChEMBL API.
drug_targets = [
  {"drug_id": "drug_imatinib", "target_id": "tgt_abl1", "affinity_nm": 25.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_imatinib", "target_id": "tgt_kit", "affinity_nm": 100.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_imatinib", "target_id": "tgt_pdgfra", "affinity_nm": 100.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_erlotinib", "target_id": "tgt_egfr", "affinity_nm": 2.0, "affinity_type": "Ki", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_gefitinib", "target_id": "tgt_egfr", "affinity_nm": 3.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_dasatinib", "target_id": "tgt_abl1", "affinity_nm": 0.6, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_dasatinib", "target_id": "tgt_src", "affinity_nm": 0.5, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_nilotinib", "target_id": "tgt_abl1", "affinity_nm": 20.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_sunitinib", "target_id": "tgt_kdr", "affinity_nm": 10.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_sunitinib", "target_id": "tgt_kit", "affinity_nm": 10.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_sorafenib", "target_id": "tgt_braf", "affinity_nm": 38.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_sorafenib", "target_id": "tgt_kdr", "affinity_nm": 90.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_lapatinib", "target_id": "tgt_egfr", "affinity_nm": 10.8, "affinity_type": "Ki", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_lapatinib", "target_id": "tgt_erbb2", "affinity_nm": 9.2, "affinity_type": "Ki", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_pazopanib", "target_id": "tgt_kdr", "affinity_nm": 30.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_pazopanib", "target_id": "tgt_flt1", "affinity_nm": 10.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_axitinib", "target_id": "tgt_kdr", "affinity_nm": 0.2, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  # illustrative off-targets for attribution demos
  {"drug_id": "drug_sunitinib", "target_id": "tgt_src", "affinity_nm": 500.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_dasatinib", "target_id": "tgt_kit", "affinity_nm": 5.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_imatinib", "target_id": "tgt_src", "affinity_nm": 450.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_imatinib", "target_id": "tgt_egfr", "affinity_nm": 800.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_imatinib", "target_id": "tgt_cyp3a4", "affinity_nm": 1200.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_erlotinib", "target_id": "tgt_erbb2", "affinity_nm": 350.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_erlotinib", "target_id": "tgt_src", "affinity_nm": 900.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_gefitinib", "target_id": "tgt_erbb2", "affinity_nm": 400.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_nilotinib", "target_id": "tgt_kit", "affinity_nm": 60.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_nilotinib", "target_id": "tgt_src", "affinity_nm": 200.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_lapatinib", "target_id": "tgt_src", "affinity_nm": 600.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_lapatinib", "target_id": "tgt_cyp3a4", "affinity_nm": 800.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_pazopanib", "target_id": "tgt_kit", "affinity_nm": 74.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_sorafenib", "target_id": "tgt_kit", "affinity_nm": 68.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_axitinib", "target_id": "tgt_kit", "affinity_nm": 1.6, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_ibrutinib", "target_id": "tgt_btk", "affinity_nm": 0.5, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_ibrutinib", "target_id": "tgt_egfr", "affinity_nm": 50.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_osimertinib", "target_id": "tgt_egfr", "affinity_nm": 1.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_tofacitinib", "target_id": "tgt_jak1", "affinity_nm": 15.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_tofacitinib", "target_id": "tgt_src", "affinity_nm": 400.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": True, "source": "seed"},
  {"drug_id": "drug_pembrolizumab", "target_id": "tgt_pdcd1", "affinity_nm": 0.1, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_dupilumab", "target_id": "tgt_il4r", "affinity_nm": 0.2, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_tozinameran", "target_id": "tgt_spike", "affinity_nm": None, "affinity_type": None, "action_type": "antigen", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_elasomeran", "target_id": "tgt_spike", "affinity_nm": None, "affinity_type": None, "action_type": "antigen", "is_off_target": False, "source": "seed"},
]

pathways = [
  {"pathway_id": "pw_egfr_signaling", "name": "EGFR signaling", "source": "seed", "tox_tag": "dermal"},
  {"pathway_id": "pw_vegfr_angiogenesis", "name": "VEGFR angiogenesis", "source": "seed", "tox_tag": "vascular"},
  {"pathway_id": "pw_abl_signaling", "name": "ABL signaling", "source": "seed", "tox_tag": None},
  {"pathway_id": "pw_hepatic_metabolism", "name": "Hepatic xenobiotic metabolism", "source": "seed", "tox_tag": "hepatotox"},
]

pathway_targets = [
  {"pathway_id": "pw_egfr_signaling", "target_id": "tgt_egfr"},
  {"pathway_id": "pw_egfr_signaling", "target_id": "tgt_erbb2"},
  {"pathway_id": "pw_vegfr_angiogenesis", "target_id": "tgt_kdr"},
  {"pathway_id": "pw_vegfr_angiogenesis", "target_id": "tgt_flt1"},
  {"pathway_id": "pw_abl_signaling", "target_id": "tgt_abl1"},
  {"pathway_id": "pw_hepatic_metabolism", "target_id": "tgt_cyp3a4"},
  {"pathway_id": "pw_hepatic_metabolism", "target_id": "tgt_cyp2d6"},
]

ae_terms = [
  {"ae_term_id": "ae_rash", "pt_string": "Rash", "soc": "Skin and subcutaneous tissue disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_diarrhoea", "pt_string": "Diarrhoea", "soc": "Gastrointestinal disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_nausea", "pt_string": "Nausea", "soc": "Gastrointestinal disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_hepatotoxicity", "pt_string": "Hepatotoxicity", "soc": "Hepatobiliary disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_drug_induced_liver_injury", "pt_string": "Drug-induced liver injury", "soc": "Hepatobiliary disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_alanine_aminotransferase_increased", "pt_string": "Alanine aminotransferase increased", "soc": "Investigations", "source": "openfda_pt"},
  {"ae_term_id": "ae_qt_prolonged", "pt_string": "Electrocardiogram QT prolonged", "soc": "Investigations", "source": "openfda_pt"},
  {"ae_term_id": "ae_hand_foot", "pt_string": "Palmar-plantar erythrodysaesthesia syndrome", "soc": "Skin and subcutaneous tissue disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_hypertension", "pt_string": "Hypertension", "soc": "Vascular disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_interstitial_lung", "pt_string": "Interstitial lung disease", "soc": "Respiratory, thoracic and mediastinal disorders", "source": "openfda_pt"},
  {"ae_term_id": "ae_myocarditis", "pt_string": "Myocarditis", "soc": "Cardiac disorders", "meddra_pt_code": "10028606", "source": "openfda_pt"},
  {"ae_term_id": "ae_anaphylactic_reaction", "pt_string": "Anaphylactic reaction", "soc": "Immune system disorders", "meddra_pt_code": "10002198", "source": "openfda_pt"},
  {"ae_term_id": "ae_immune_mediated_colitis", "pt_string": "Immune-mediated colitis", "soc": "Gastrointestinal disorders", "meddra_pt_code": "10009887", "source": "openfda_pt"},
  {"ae_term_id": "ae_conjunctivitis", "pt_string": "Conjunctivitis", "soc": "Eye disorders", "meddra_pt_code": "10010741", "source": "openfda_pt"},
]

variants = [
  {
    "variant_id": "var_cyp2d6_star4",
    "rsid": "rs3892097",
    "gene_symbol": "CYP2D6",
    "clinvar_id": None,
    "pharmgkb_id": "PA128",
    "metabolizer_impact": "CYP2D6_PM",
    "consequence": "splicing / loss-of-function (*4)",
    "allele_freq": 0.2,
    "effect_size": 0.8,
    "related_pt": "Drug-induced liver injury",
    "notes": "Seed ADME variant for S_gen demos",
  },
  {
    "variant_id": "var_cyp3a4_star22",
    "rsid": "rs35599367",
    "gene_symbol": "CYP3A4",
    "clinvar_id": None,
    "pharmgkb_id": "PA130",
    "metabolizer_impact": "CYP3A4_IM",
    "consequence": "reduced expression (*22)",
    "allele_freq": 0.05,
    "effect_size": 0.6,
    "related_pt": "Hepatotoxicity",
    "notes": "Hepatic metabolism intermediate",
  },
  {
    "variant_id": "var_egfr_t790m",
    "rsid": "rs121434569",
    "gene_symbol": "EGFR",
    "clinvar_id": None,
    "pharmgkb_id": None,
    "metabolizer_impact": None,
    "consequence": "missense T790M",
    "allele_freq": 0.0,
    "effect_size": 0.5,
    "related_pt": "Interstitial lung disease",
    "notes": "Resistance / on-target biology seed",
  },
]

crosswalks = [
  # drug: RxNorm ↔ ChEMBL
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "282388", "to_system": "chembl", "to_id": "CHEMBL941", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "337525", "to_system": "chembl", "to_id": "CHEMBL553", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "328134", "to_system": "chembl", "to_id": "CHEMBL939", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "668700", "to_system": "chembl", "to_id": "CHEMBL1421", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "662281", "to_system": "chembl", "to_id": "CHEMBL1168", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "616739", "to_system": "chembl", "to_id": "CHEMBL535", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "495881", "to_system": "chembl", "to_id": "CHEMBL1336", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "480167", "to_system": "chembl", "to_id": "CHEMBL554", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "891656", "to_system": "chembl", "to_id": "CHEMBL119929", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1242988", "to_system": "chembl", "to_id": "CHEMBL1289926", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1442986", "to_system": "chembl", "to_id": "CHEMBL1873475", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1727455", "to_system": "chembl", "to_id": "CHEMBL3353410", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1356511", "to_system": "chembl", "to_id": "CHEMBL221959", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "2468231", "to_system": "chembl", "to_id": "CHEMBL4297850", "confidence": 0.8},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "2473488", "to_system": "chembl", "to_id": "CHEMBL4297851", "confidence": 0.8},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1547545", "to_system": "chembl", "to_id": "CHEMBL3137343", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1873983", "to_system": "chembl", "to_id": "CHEMBL1743036", "confidence": 1.0},
  # target: UniProt ↔ Ensembl
  {"entity_type": "target", "from_system": "uniprot", "from_id": "P00533", "to_system": "ensembl", "to_id": "ENSG00000146648", "confidence": 1.0},
  {"entity_type": "target", "from_system": "uniprot", "from_id": "P00519", "to_system": "ensembl", "to_id": "ENSG00000097007", "confidence": 1.0},
  {"entity_type": "target", "from_system": "uniprot", "from_id": "P35968", "to_system": "ensembl", "to_id": "ENSG00000128052", "confidence": 1.0},
  {"entity_type": "target", "from_system": "uniprot", "from_id": "P10635", "to_system": "ensembl", "to_id": "ENSG00000100146", "confidence": 1.0},
  # ae: openFDA PT string identity map (MedDRA code deferred)
  {"entity_type": "ae", "from_system": "openfda_pt", "from_id": "Rash", "to_system": "openfda_pt", "to_id": "Rash", "confidence": 1.0},
  {"entity_type": "ae", "from_system": "openfda_pt", "from_id": "Hepatotoxicity", "to_system": "openfda_pt", "to_id": "Hepatotoxicity", "confidence": 1.0},
  {"entity_type": "ae", "from_system": "openfda_pt", "from_id": "Drug-induced liver injury", "to_system": "openfda_pt", "to_id": "Drug-induced liver injury", "confidence": 1.0},
]

# Phase 4 validation seeds — known labeled risks for kinase class
ground_truth = [
  {"drug_id": "drug_lapatinib", "ae_term_id": "ae_hepatotoxicity", "label_type": "black_box", "source": "FDA label Tykerb", "notes": "Hepatotoxicity BBW"},
  {"drug_id": "drug_pazopanib", "ae_term_id": "ae_hepatotoxicity", "label_type": "black_box", "source": "FDA label Votrient", "notes": "Hepatotoxicity BBW"},
  {"drug_id": "drug_nilotinib", "ae_term_id": "ae_qt_prolonged", "label_type": "black_box", "source": "FDA label Tasigna", "notes": "QT prolongation BBW"},
  {"drug_id": "drug_gefitinib", "ae_term_id": "ae_interstitial_lung", "label_type": "known", "source": "FDA label Iressa", "notes": "ILD warning"},
  {"drug_id": "drug_erlotinib", "ae_term_id": "ae_interstitial_lung", "label_type": "known", "source": "FDA label Tarceva", "notes": "ILD warning"},
  {"drug_id": "drug_sorafenib", "ae_term_id": "ae_hand_foot", "label_type": "known", "source": "FDA label Nexavar", "notes": "HFSR common AE"},
  {"drug_id": "drug_sunitinib", "ae_term_id": "ae_hypertension", "label_type": "known", "source": "FDA label Sutent", "notes": "Hypertension common with VEGFR TKIs"},
  {"drug_id": "drug_tozinameran", "ae_term_id": "ae_myocarditis", "label_type": "known", "source": "FDA fact sheet Comirnaty", "notes": "Myocarditis / pericarditis warning"},
  {"drug_id": "drug_elasomeran", "ae_term_id": "ae_myocarditis", "label_type": "known", "source": "FDA fact sheet Spikevax", "notes": "Myocarditis / pericarditis warning"},
  {"drug_id": "drug_pembrolizumab", "ae_term_id": "ae_immune_mediated_colitis", "label_type": "known", "source": "FDA label Keytruda", "notes": "Immune-mediated adverse reactions"},
  {"drug_id": "drug_dupilumab", "ae_term_id": "ae_conjunctivitis", "label_type": "known", "source": "FDA label Dupixent", "notes": "Conjunctivitis common AE"},
]
