"""Portfolio fill for sponsors that otherwise return 0 rows in the UI filter.

IDs curated from FDA Orange Book / Purple Book / openFDA / RxNorm public catalogs.
Join grain remains drug ↔ target ↔ openFDA PT.
"""

from __future__ import annotations

# Flagship product per previously empty SPONSOR_DIRECTORY entry
drugs = [
  {
    "drug_id": "drug_sotorasib",
    "preferred_name": "sotorasib",
    "brand_name": "Lumakras",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Amgen",
    "nda_bla": "NDA214665",
    "atc_code": "L01XX73",
    "rxnorm_cui": "2556674",
    "chembl_id": "CHEMBL4559787",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "KRAS G12C inhibitor (Amgen Lumakras) — FDA NDA / openFDA",
  },
  {
    "drug_id": "drug_natalizumab",
    "preferred_name": "natalizumab",
    "brand_name": "Tysabri",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "neurology",
    "molecule_type": "biologic",
    "sponsor_company": "Biogen",
    "nda_bla": "BLA125104",
    "atc_code": "L04AA23",
    "rxnorm_cui": "354770",
    "chembl_id": "CHEMBL1201581",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-α4 integrin mAb (Biogen Tysabri) — PML BBW",
  },
  {
    "drug_id": "drug_nintedanib",
    "preferred_name": "nintedanib",
    "brand_name": "Ofev",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "pulmonary",
    "molecule_type": "small_molecule",
    "sponsor_company": "Boehringer Ingelheim",
    "nda_bla": "NDA205832",
    "atc_code": "L01EX09",
    "rxnorm_cui": "1592737",
    "chembl_id": "CHEMBL502835",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "Multi-kinase TKI (Boehringer Ofev) — IPF",
  },
  {
    "drug_id": "drug_baricitinib",
    "preferred_name": "baricitinib",
    "brand_name": "Olumiant",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "immunology",
    "molecule_type": "small_molecule",
    "sponsor_company": "Eli Lilly",
    "nda_bla": "NDA207924",
    "atc_code": "L04AA37",
    "rxnorm_cui": "1927851",
    "chembl_id": "CHEMBL2105759",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "JAK1/2 inhibitor (Eli Lilly Olumiant)",
  },
  {
    "drug_id": "drug_remdesivir",
    "preferred_name": "remdesivir",
    "brand_name": "Veklury",
    "drug_class": "antiviral",
    "therapeutic_class": "infectious_disease",
    "molecule_type": "small_molecule",
    "sponsor_company": "Gilead Sciences",
    "nda_bla": "NDA214787",
    "atc_code": "J05AB16",
    "rxnorm_cui": "2284762",
    "chembl_id": "CHEMBL4065616",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "RdRp inhibitor (Gilead Veklury)",
  },
  {
    "drug_id": "drug_trametinib",
    "preferred_name": "trametinib",
    "brand_name": "Mekinist",
    "drug_class": "kinase_inhibitor",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "small_molecule",
    "sponsor_company": "GSK (GlaxoSmithKline)",
    "nda_bla": "NDA204114",
    "atc_code": "L01EE01",
    "rxnorm_cui": "1422430",
    "chembl_id": "CHEMBL2103875",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "MEK1/2 inhibitor (GSK Mekinist)",
  },
  {
    "drug_id": "drug_daratumumab",
    "preferred_name": "daratumumab",
    "brand_name": "Darzalex",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "hematologic_oncology",
    "molecule_type": "biologic",
    "sponsor_company": "Johnson & Johnson (Janssen)",
    "nda_bla": "BLA761036",
    "atc_code": "L01FC01",
    "rxnorm_cui": "1723735",
    "chembl_id": "CHEMBL1743007",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-CD38 mAb (Janssen Darzalex)",
  },
  {
    "drug_id": "drug_cemiplimab",
    "preferred_name": "cemiplimab",
    "brand_name": "Libtayo",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "solid_tumor_oncology",
    "molecule_type": "biologic",
    "sponsor_company": "Regeneron",
    "nda_bla": "BLA761097",
    "atc_code": "L01FF06",
    "rxnorm_cui": "2058844",
    "chembl_id": "CHEMBL4297867",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-PD-1 mAb (Regeneron Libtayo)",
  },
  {
    "drug_id": "drug_vedolizumab",
    "preferred_name": "vedolizumab",
    "brand_name": "Entyvio",
    "drug_class": "monoclonal_antibody",
    "therapeutic_class": "immunology",
    "molecule_type": "biologic",
    "sponsor_company": "Takeda",
    "nda_bla": "BLA125476",
    "atc_code": "L04AA33",
    "rxnorm_cui": "1534763",
    "chembl_id": "CHEMBL1743034",
    "is_mvp_seed": True,
    "cyp_substrates": None,
    "notes": "Anti-α4β7 integrin mAb (Takeda Entyvio)",
  },
  {
    "drug_id": "drug_ivacaftor",
    "preferred_name": "ivacaftor",
    "brand_name": "Kalydeco",
    "drug_class": "cftr_modulator",
    "therapeutic_class": "pulmonary",
    "molecule_type": "small_molecule",
    "sponsor_company": "Vertex Pharmaceuticals",
    "nda_bla": "NDA203188",
    "atc_code": "R07AX02",
    "rxnorm_cui": "1242987",
    "chembl_id": "CHEMBL2010601",
    "is_mvp_seed": True,
    "cyp_substrates": "CYP3A4",
    "notes": "CFTR potentiator (Vertex Kalydeco)",
  },
]

targets = [
  {"target_id": "tgt_kras", "gene_symbol": "KRAS", "uniprot_id": "P01116", "ensembl_id": "ENSG00000133703", "pdb_id": "4OBE", "protein_name": "GTPase KRas", "is_admet_relevant": False},
  {"target_id": "tgt_itga4", "gene_symbol": "ITGA4", "uniprot_id": "P13612", "ensembl_id": "ENSG00000115232", "pdb_id": "1GCQ", "protein_name": "Integrin alpha-4", "is_admet_relevant": False},
  {"target_id": "tgt_map2k1", "gene_symbol": "MAP2K1", "uniprot_id": "Q02750", "ensembl_id": "ENSG00000169032", "pdb_id": "3EQC", "protein_name": "MAP kinase kinase 1", "is_admet_relevant": False},
  {"target_id": "tgt_cd38", "gene_symbol": "CD38", "uniprot_id": "P28907", "ensembl_id": "ENSG00000004468", "pdb_id": "1YH3", "protein_name": "ADP-ribosyl cyclase/cyclic ADP-ribose hydrolase 1", "is_admet_relevant": False},
  {"target_id": "tgt_itgb7", "gene_symbol": "ITGB7", "uniprot_id": "P26010", "ensembl_id": "ENSG00000139626", "pdb_id": "3V4P", "protein_name": "Integrin beta-7", "is_admet_relevant": False},
  {"target_id": "tgt_cftr", "gene_symbol": "CFTR", "uniprot_id": "P13569", "ensembl_id": "ENSG00000001626", "pdb_id": "5UAK", "protein_name": "Cystic fibrosis transmembrane conductance regulator", "is_admet_relevant": False},
  {"target_id": "tgt_nsp12", "gene_symbol": "nsp12", "uniprot_id": "P0DTD1", "ensembl_id": None, "pdb_id": "7BV2", "protein_name": "SARS-CoV-2 RNA-dependent RNA polymerase", "is_admet_relevant": False},
]

drug_targets = [
  {"drug_id": "drug_sotorasib", "target_id": "tgt_kras", "affinity_nm": 7.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_natalizumab", "target_id": "tgt_itga4", "affinity_nm": 0.3, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_nintedanib", "target_id": "tgt_kdr", "affinity_nm": 21.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_baricitinib", "target_id": "tgt_jak1", "affinity_nm": 5.7, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_remdesivir", "target_id": "tgt_nsp12", "affinity_nm": 10.0, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_trametinib", "target_id": "tgt_map2k1", "affinity_nm": 0.9, "affinity_type": "IC50", "action_type": "inhibitor", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_daratumumab", "target_id": "tgt_cd38", "affinity_nm": 0.2, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_cemiplimab", "target_id": "tgt_pdcd1", "affinity_nm": 0.1, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_vedolizumab", "target_id": "tgt_itgb7", "affinity_nm": 0.4, "affinity_type": "Kd", "action_type": "antagonist", "is_off_target": False, "source": "seed"},
  {"drug_id": "drug_ivacaftor", "target_id": "tgt_cftr", "affinity_nm": 100.0, "affinity_type": "EC50", "action_type": "potentiator", "is_off_target": False, "source": "seed"},
]

ae_terms = [
  {"ae_term_id": "ae_pml", "pt_string": "Progressive multifocal leukoencephalopathy", "soc": "Infections and infestations", "meddra_pt_code": "10036814", "source": "openfda_pt"},
  {"ae_term_id": "ae_hypersensitivity", "pt_string": "Hypersensitivity", "soc": "Immune system disorders", "meddra_pt_code": "10020765", "source": "openfda_pt"},
  {"ae_term_id": "ae_infection", "pt_string": "Infection", "soc": "Infections and infestations", "meddra_pt_code": "10021881", "source": "openfda_pt"},
  {"ae_term_id": "ae_thrombosis", "pt_string": "Thrombosis", "soc": "Vascular disorders", "meddra_pt_code": "10043607", "source": "openfda_pt"},
  {"ae_term_id": "ae_infusion_reaction", "pt_string": "Infusion related reaction", "soc": "Injury, poisoning and procedural complications", "meddra_pt_code": "10051792", "source": "openfda_pt"},
  {"ae_term_id": "ae_neutropenia", "pt_string": "Neutropenia", "soc": "Blood and lymphatic system disorders", "meddra_pt_code": "10029354", "source": "openfda_pt"},
  {"ae_term_id": "ae_cardiomyopathy", "pt_string": "Cardiomyopathy", "soc": "Cardiac disorders", "meddra_pt_code": "10007636", "source": "openfda_pt"},
  {"ae_term_id": "ae_nasopharyngitis", "pt_string": "Nasopharyngitis", "soc": "Infections and infestations", "meddra_pt_code": "10028810", "source": "openfda_pt"},
  {"ae_term_id": "ae_headache", "pt_string": "Headache", "soc": "Nervous system disorders", "meddra_pt_code": "10019211", "source": "openfda_pt"},
]

# name -> primary AEs for FAERS fixture generation
PRIMARY_AES = {
  "sotorasib": ["Diarrhoea", "Hepatotoxicity", "Nausea"],
  "natalizumab": ["Progressive multifocal leukoencephalopathy", "Hypersensitivity", "Hepatotoxicity"],
  "nintedanib": ["Diarrhoea", "Nausea", "Hepatotoxicity"],
  "baricitinib": ["Infection", "Thrombosis", "Hepatotoxicity"],
  "remdesivir": ["Hepatotoxicity", "Nausea", "Infusion related reaction"],
  "trametinib": ["Rash", "Diarrhoea", "Cardiomyopathy"],
  "daratumumab": ["Infusion related reaction", "Infection", "Neutropenia"],
  "cemiplimab": ["Immune-mediated colitis", "Rash", "Hepatotoxicity"],
  "vedolizumab": ["Infection", "Nasopharyngitis", "Hepatotoxicity"],
  "ivacaftor": ["Hepatotoxicity", "Headache", "Rash"],
}

DOSES = {
  "sotorasib": "960 mg",
  "natalizumab": "300 mg IV",
  "nintedanib": "150 mg",
  "baricitinib": "2 mg",
  "remdesivir": "100 mg IV",
  "trametinib": "2 mg",
  "daratumumab": "16 mg/kg IV",
  "cemiplimab": "350 mg IV",
  "vedolizumab": "300 mg IV",
  "ivacaftor": "150 mg",
}

ground_truth = [
  {"drug_id": "drug_natalizumab", "ae_term_id": "ae_pml", "label_type": "black_box", "source": "FDA label Tysabri", "notes": "PML BBW"},
  {"drug_id": "drug_baricitinib", "ae_term_id": "ae_thrombosis", "label_type": "black_box", "source": "FDA label Olumiant", "notes": "Thrombosis / serious infection BBW"},
  {"drug_id": "drug_sotorasib", "ae_term_id": "ae_hepatotoxicity", "label_type": "known", "source": "FDA label Lumakras", "notes": "Hepatotoxicity warning"},
  {"drug_id": "drug_ivacaftor", "ae_term_id": "ae_hepatotoxicity", "label_type": "known", "source": "FDA label Kalydeco", "notes": "Hepatic monitoring"},
]

crosswalks = [
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "2556674", "to_system": "chembl", "to_id": "CHEMBL4559787", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "354770", "to_system": "chembl", "to_id": "CHEMBL1201581", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1592737", "to_system": "chembl", "to_id": "CHEMBL502835", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1927851", "to_system": "chembl", "to_id": "CHEMBL2105759", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "2284762", "to_system": "chembl", "to_id": "CHEMBL4065616", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1422430", "to_system": "chembl", "to_id": "CHEMBL2103875", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1723735", "to_system": "chembl", "to_id": "CHEMBL1743007", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "2058844", "to_system": "chembl", "to_id": "CHEMBL4297867", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1534763", "to_system": "chembl", "to_id": "CHEMBL1743034", "confidence": 1.0},
  {"entity_type": "drug", "from_system": "rxnorm", "from_id": "1242987", "to_system": "chembl", "to_id": "CHEMBL2010601", "confidence": 1.0},
]
